language: 
  - python

# https://docs.travis-ci.com/user/gui-and-headless-browsers/
services:
  - xvfb

install:
  - pip install -r requirements.txt

#before_script:
#  - export PYTHONPATH=$PYTHONPATH:$(pwd)/surgeo/

script:
  - python ./tests/test_runner.py
