os:
  - windows
  - osx
  - linux

language: 
  - python

install:
  - pip install -r requirements.txt
  - pip install cx_Freeze

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/surgeo/

script:
  - python ./tests/test_runner.py
