language: python

# https://docs.travis-ci.com/user/gui-and-headless-browsers/
services:
  - xvfb

install:
  - pip install -r requirements.txt
  - python setup.py install

#before_script:
#  - export PYTHONPATH=$PYTHONPATH:$(pwd)/surgeo/

script:
  - python ./tests/test_runner.py

virtualenv:
  system_site_packages: true
